#!/usr/bin/python
# ******************************************************************************
# Copyright (c) 2020-2021, Virtuozzo International GmbH.
# This source code is distributed under MIT software license.
# ******************************************************************************

import cloudblue_connector.runners as runners


if __name__ == '__main__':
    rv = runners.process_fulfillment()
    print(rv)
