#!/usr/bin/python
#******************************************************************************
# Copyright (c) 2020, Virtuozzo International GmbH.
# This source code is distributed under MIT software license.
#******************************************************************************

import cloudblue_connector as connector


if __name__ == '__main__':
    rv = connector.process_fulfillment()
    print(rv)
